spring:
    application:
        name: dubbo-provider
server:
  port: 8001

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.1.234:2181
  scan:
    base-packages: 'com.dubbo.provider.service'